### ISSUE TITLE
[Feature Request] switch input method bulit-in ascii_mode

### ISSUE THREAD

**Issue by tuberry** [kevinhwang91/vim-ibus-sw#3]
Can DBus change the  ascii_mode of IME (e.g.  libpinyin)? If possible, it's better to use English in command mode and remain the state in insert mode, after all, we'd used to use `Shift` rather than `Win+Space` to switch state. By the way, It doesn't work well with systray, how can I turn the debug message on?

**Comment by kevinhwang91** [comment]
> Can DBus change the ascii_mode of IME (e.g. libpinyin)? 

I don't think it could switch ascii_mode by sending cmd to D-Bus, It relates to your IME but not D-Bus. 

> By the way, It doesn't work well with systray

It seems that the plugin using `ibus engine` instead of `dbus-send`. What's your `DESKTOP_SESSION` of env value?  `[[ $DESKTOP_SESSION == "gnome" && -x $(command -v dbus-send) ]]` if true will use `dbus-send`, other wise `ibus engine`.

I have tested on KDE that works, so I will delete the condition code about gnome. Maybe I will delete the redundant code about switching using `ibus engine`, because `ibus` depend on `dbus`, and `dbus` including `dbus-send`(information from arch linux `pacman`).

>how can I turn the debug message on?
There isn't any debug code in the source. It's hard code for echo message in demo. I'm so sorry about that.

Finally, thank you for your report.

**Comment by kevinhwang91** [comment]
> Can DBus change the ascii_mode of IME (e.g. libpinyin)? 

I don't think it could switch ascii_mode by sending cmd to D-Bus, It relates to your IME but not D-Bus. 

> By the way, It doesn't work well with systray

It seems that the plugin using `ibus engine` instead of `dbus-send`. What's your `DESKTOP_SESSION` of env value?  `[[ $DESKTOP_SESSION == "gnome" && -x $(command -v dbus-send) ]]` if true will use `dbus-send`, other wise `ibus engine`.
You can run shell under bin directory. such as `init.sh`, if value of `itype` equal 'dbus',vim will exec `dbus_ibus_switch.sh` get_input or set_input.

>how can I turn the debug message on?

There isn't any debug code in the source. It's hard code for echo message in demo. I'm so sorry about that.

Finally, thank you for your report.

**Comment by tuberry** [comment]
It is `gnome-xorg`,  please update to support. Thanks.
